function [Cold_Humid , Cold_Dry] = Fig1b_TransferMatrix(AI_PM_RC_Princeton , AI_PM_RC_CO2_Yang_Princeton ,...
    AI_PM_RC_CO2_Jarvis_H_Princeton , AI_PM_RC_2070_2099 ,...
    AI_PM_RC_CO2_Yang_2070_2099 , AI_PM_RC_CO2_Jarvis_H_2070_2099 ,...
    Path_Fig1b_Output , sspName)
% Adjust map range from 0~360 to -180~180
load EarthLandArea_05deg
A = EarthLandArea_05deg(1:360 , :);
B = EarthLandArea_05deg(361:end , :);
EarthLandArea_05deg = [B;A]; clear B A

% Humid 1; Hyper_arid 5; Arid 4; Semi_arid 3; Dry_Sub_humid 2; Cold 6;
AI_PM_RC_2070_2099(AI_PM_RC_2070_2099==-9999)=nan;
AI_PM_RC_CO2_Yang_2070_2099(AI_PM_RC_CO2_Yang_2070_2099==-9999)=nan;
AI_PM_RC_CO2_Jarvis_H_2070_2099(AI_PM_RC_CO2_Jarvis_H_2070_2099==-9999)=nan;

AI_PM_RC_Princeton(AI_PM_RC_Princeton==-9999)=nan;
AI_PM_RC_CO2_Yang_Princeton(AI_PM_RC_CO2_Yang_Princeton==-9999)=nan;
AI_PM_RC_CO2_Jarvis_H_Princeton(AI_PM_RC_CO2_Jarvis_H_Princeton==-9999)=nan;

AI_PM_RC_Change = AI_PM_RC_Princeton.*10 + AI_PM_RC_2070_2099;
AI_PM_RC_CO2_Yang_Change = AI_PM_RC_CO2_Yang_Princeton.*10 + AI_PM_RC_CO2_Yang_2070_2099;
AI_PM_RC_CO2_Jarvis_H_Change = AI_PM_RC_CO2_Jarvis_H_Princeton.*10 + AI_PM_RC_CO2_Jarvis_H_2070_2099;

%% PM_RC_Jarvis_H
% 1948-2014 Humid converted to What
M_PM_RC_Jarvis_H(1,:) =...
    [nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==11)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==1)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==12)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==1)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==13)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==1)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==14)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==1)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==15)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==1)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==16)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==1)) .*100];
% 1948-2014 subhumid converted to What
M_PM_RC_Jarvis_H(2,:) =...
    [nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==21)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==2)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==22)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==2)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==23)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==2)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==24)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==2)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==25)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==2)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==26)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==2)) .*100];
% 1948-2014 3 converted to What
M_PM_RC_Jarvis_H(3,:) =...
    [nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==31)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==3)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==32)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==3)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==33)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==3)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==34)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==3)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==35)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==3)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==36)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==3)) .*100];
% 1948-2014 4 converted to What
M_PM_RC_Jarvis_H(4,:) =...
    [nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==41)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==4)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==42)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==4)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==43)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==4)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==44)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==4)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==45)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==4)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==46)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==4)) .*100];
% 1948-2014 hyper-aird converted to What
M_PM_RC_Jarvis_H(5,:) =...
    [nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==51)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==5)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==52)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==5)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==53)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==5)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==54)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==5)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==55)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==5)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==56)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==5)) .*100];
% 1948-2014 Cold converted to What
M_PM_RC_Jarvis_H(6,:) =...
    [nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==61)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==6)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==62)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==6)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==63)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==6)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==64)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==6)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==65)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==6)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==66)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Princeton==6)) .*100];


%% PM_RC_Yang
% 1948-2014 Humid converted to What
M_PM_RC_Yang(1,:) =...
    [nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==11)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==1)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==12)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==1)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==13)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==1)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==14)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==1)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==15)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==1)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==16)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==1)) .*100];
% 1948-2014 subhumid converted to What
M_PM_RC_Yang(2,:) =...
    [nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==21)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==2)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==22)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==2)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==23)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==2)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==24)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==2)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==25)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==2)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==26)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==2)) .*100];
% 1948-2014 3 converted to What
M_PM_RC_Yang(3,:) =...
    [nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==31)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==3)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==32)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==3)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==33)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==3)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==34)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==3)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==35)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==3)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==36)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==3)) .*100];
% 1948-2014 4 converted to What
M_PM_RC_Yang(4,:) =...
    [nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==41)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==4)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==42)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==4)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==43)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==4)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==44)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==4)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==45)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==4)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==46)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==4)) .*100];
% 1948-2014 hyper-aird converted to What
M_PM_RC_Yang(5,:) =...
    [nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==51)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==5)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==52)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==5)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==53)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==5)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==54)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==5)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==55)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==5)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==56)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==5)) .*100];
% 1948-2014 Cold converted to What
M_PM_RC_Yang(6,:) =...
    [nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==61)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==6)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==62)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==6)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==63)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==6)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==64)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==6)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==65)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==6)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Change==66)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Yang_Princeton==6)) .*100];

%% PM_RC
% 1948-2014 Humid converted to What
M_PM_RC(1,:) =...
    [nansum(EarthLandArea_05deg(AI_PM_RC_Change==11)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==1)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==12)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==1)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==13)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==1)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==14)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==1)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==15)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==1)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==16)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==1)) .*100];
% 1948-2014 subhumid converted to What
M_PM_RC(2,:) =...
    [nansum(EarthLandArea_05deg(AI_PM_RC_Change==21)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==2)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==22)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==2)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==23)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==2)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==24)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==2)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==25)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==2)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==26)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==2)) .*100];
% 1948-2014 3 converted to What
M_PM_RC(3,:) =...
    [nansum(EarthLandArea_05deg(AI_PM_RC_Change==31)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==3)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==32)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==3)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==33)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==3)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==34)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==3)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==35)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==3)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==36)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==3)) .*100];
% 1948-2014 4 converted to What
M_PM_RC(4,:) =...
    [nansum(EarthLandArea_05deg(AI_PM_RC_Change==41)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==4)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==42)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==4)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==43)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==4)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==44)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==4)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==45)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==4)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==46)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==4)) .*100];
% 1948-2014 hyper-aird converted to What
M_PM_RC(5,:) =...
    [nansum(EarthLandArea_05deg(AI_PM_RC_Change==51)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==5)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==52)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==5)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==53)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==5)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==54)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==5)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==55)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==5)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==56)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==5)) .*100];
% 1948-2014 Cold converted to What
M_PM_RC(6,:) =...
    [nansum(EarthLandArea_05deg(AI_PM_RC_Change==61)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==6)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==62)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==6)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==63)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==6)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==64)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==6)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==65)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==6)) .*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_Change==66)) ./ nansum(EarthLandArea_05deg(AI_PM_RC_Princeton==6)) .*100];

xlswrite([Path_Fig1b_Output 'TransferMatrix_EnsembleMean.xlsx'] , M_PM_RC , sspName , 'C4:H9');
xlswrite([Path_Fig1b_Output 'TransferMatrix_EnsembleMean.xlsx'] , M_PM_RC_Yang , sspName , 'C16:H21');
xlswrite([Path_Fig1b_Output 'TransferMatrix_EnsembleMean.xlsx'] , M_PM_RC_Jarvis_H , sspName , 'C28:H33');


load Permafrost
% permafrost: 5-Continuous,4-sporadic,3-discontinuous,2-isolated.
Permafrost = fliplr(Permafrost');
% From 1948-2014 to 2070-2099, How much Permafrost Transfer from Cold to Humid & Dry
% P51 = nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==61&Permafrost==5))./nansum(EarthLandArea_05deg(~isnan(Permafrost))).*100;
% P41 = nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==61&Permafrost==4))./nansum(EarthLandArea_05deg(~isnan(Permafrost))).*100;
% P31 = nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==61&Permafrost==3))./nansum(EarthLandArea_05deg(~isnan(Permafrost))).*100;
% P21 = nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==61&Permafrost==2))./nansum(EarthLandArea_05deg(~isnan(Permafrost))).*100;
% Cold_Humid = [P51,P31,P41,P21];
% 
% Cold_Dry = sum([nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==62&~isnan(Permafrost)))./nansum(EarthLandArea_05deg(~isnan(Permafrost))).*100,...
%     nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==63&~isnan(Permafrost)))./nansum(EarthLandArea_05deg(~isnan(Permafrost))).*100,...
%     nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==64&~isnan(Permafrost)))./nansum(EarthLandArea_05deg(~isnan(Permafrost))).*100,...
%     nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_Change==65&~isnan(Permafrost)))./nansum(EarthLandArea_05deg(~isnan(Permafrost))).*100]);

% As of 2070-2099, How much Permafrost is Humid & Dry
P51 = nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_2070_2099==1&Permafrost==5))./nansum(EarthLandArea_05deg(~isnan(Permafrost))).*100;
P41 = nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_2070_2099==1&Permafrost==4))./nansum(EarthLandArea_05deg(~isnan(Permafrost))).*100;
P31 = nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_2070_2099==1&Permafrost==3))./nansum(EarthLandArea_05deg(~isnan(Permafrost))).*100;
P21 = nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_2070_2099==1&Permafrost==2))./nansum(EarthLandArea_05deg(~isnan(Permafrost))).*100;
Cold_Humid = [P51,P31,P41,P21];

Cold_Dry = sum([nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_2070_2099==2&~isnan(Permafrost)))./nansum(EarthLandArea_05deg(~isnan(Permafrost))).*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_2070_2099==3&~isnan(Permafrost)))./nansum(EarthLandArea_05deg(~isnan(Permafrost))).*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_2070_2099==4&~isnan(Permafrost)))./nansum(EarthLandArea_05deg(~isnan(Permafrost))).*100,...
    nansum(EarthLandArea_05deg(AI_PM_RC_CO2_Jarvis_H_2070_2099==5&~isnan(Permafrost)))./nansum(EarthLandArea_05deg(~isnan(Permafrost))).*100]);
end